import { Button } from '@/components'
import { Heading } from '@components/heading/Heading'

export default function Home() {
  return (
    <>
      <Heading description={'Next App'} title={'Generated by create next app'} />
      <>
        <h1>Example Page</h1>
        <Button />
      </>
    </>
  )
}
