import { HeadMeta, getLayout } from '@/components'

const Home = () => {
  return (
    <>
      <HeadMeta description={'Next App'} title={'Generated by create next app'} />
      <h1>Main Page</h1>
    </>
  )
}

Home.getLayout = getLayout

export default Home
